requires 'Syntax::Keyword::Try', '>= 0.24';
requires 'Log::Any', '>= 1.709';
requires 'Log::Any::Adapter', '>= 1.709';
requires 'YAML::XS', '>= 0.83';
requires 'JSON::MaybeUTF8', '>= 2.000';
requires 'Unicode::UTF8';
requires 'Time::Moment', '>= 0.44';
requires 'Sys::Hostname';
requires 'Getopt::Long';
requires 'Pod::Usage';
requires 'List::Util', '>= 1.56';
requires 'Path::Tiny';
