global:
  #  scrape_inteval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-codensmoke'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
#rule_files:
#  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pushgateway'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'cloudflare'
    scrape_interval: 15s
    static_configs:
      - targets: ['cloudflare-exporter:8080']

  - job_name: 'caddy'
    scrape_interval: 15s
    static_configs:
      - targets: ['caddy-config_caddy_1:2020']

  - job_name: 'rocket_chat_app'
    scrape_interval: 15s
    static_configs:
      - targets: ['rocketchat_rocketchat_1:9458']

  - job_name: 'rocket_chat_db'
    scrape_interval: 15s
    static_configs:
      - targets: ['rocketchat_mongodb-exporter:9001']
        #  - job_name: 'redis_exporter_targets'
        #    file_sd_configs:
        #      - files:
        #        - targets-redis-instances.json
        #    metrics_path: /scrape
        #    relabel_configs:
        #      - source_labels: [__address__]
        #        target_label: __param_target
        #      - source_labels: [__param_target]
        #        target_label: instance
        #      - target_label: __address__
        #        replacement: redis_exporter:9121
        #
        #  ## config for scraping the exporter itself
        #  - job_name: 'redis_exporter'
        #    static_configs:
        #      - targets:
        #        - redis_exporter:9121
        #
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - 'alertmanager:9093'
