{
 "title": "RocketChat",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "deployment",
    "query": "label_values(nodejs_active_handles_total,DeploymentName)"
   }
  ]
 },
 "panels": [
  { "title": "Totals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Users Online",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    { "expr": "max(rocketchat_users_online)" }
   ]
  },
  {
   "title": "Users Away",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    { "expr": "max(rocketchat_users_away)" }
   ]
  },
  {
   "title": "DDP Users",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rocketchat_ddp_connected_users)"
    }
   ]
  },
  {
   "title": "Users",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 4 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    { "expr": "max(rocketchat_users_total)" }
   ]
  },
  {
   "title": "Rooms",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 4 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    { "expr": "max(rocketchat_rooms_total)" }
   ]
  },
  {
   "title": "Messages",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 4 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    { "expr": "max(rocketchat_messages_total)" }
   ]
  },
  {
   "title": "Users Diff",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 7 },
   "format": "locale",
   "valueName": "diff",
   "targets": [
    { "expr": "max(rocketchat_users_total)" }
   ]
  },
  {
   "title": "Rooms  Diff",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 7 },
   "format": "locale",
   "valueName": "diff",
   "targets": [
    { "expr": "max(rocketchat_rooms_total)" }
   ]
  },
  {
   "title": "Messages  Diff",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 7 },
   "format": "locale",
   "valueName": "diff",
   "targets": [
    { "expr": "max(rocketchat_messages_total)" }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Metrics Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(rocketchat_metrics_requests[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Metrics Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "rocketchat_metrics_size", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "NodeJS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Active Handles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nodejs_active_handles_total", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Active Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nodejs_active_requests_total", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Event loop lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nodejs_eventloop_lag_seconds", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Heap used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (space) (nodejs_heap_size_used_bytes)",
     "legendFormat": "{{space}}"
    }
   ]
  },
  {
   "title": "Per pod heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "nodejs_heap_size_used_bytes", "legendFormat": "{{instance}} [{{space}}]" }
   ]
  },
  {
   "title": "GC - Seconds Running",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nodejs_gc_pause_seconds_total[5m])) by (gctype)",
     "legendFormat": "{{gctype}}"
    }
   ]
  },
  {
   "title": "GC - Bytes Freed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nodejs_gc_reclaimed_bytes_total[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DDP Rate Limiter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Limit by type",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(rocketchat_ddp_rate_limit_exceeded{DeploymentName=\"$deployment\", user_id!=\"null\"}[5m])) by (limit_name)",
       "legendFormat": "{{limit_name}} (not null)"
      },
      {
       "expr": "sum(increase(rocketchat_ddp_rate_limit_exceeded{DeploymentName=\"$deployment\", user_id=\"null\"}[5m])) by (limit_name)",
       "legendFormat": "{{limit_name}} (null)"
      }
     ]
    },
    {
     "title": "Limit by method",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(rocketchat_ddp_rate_limit_exceeded{DeploymentName=\"$deployment\", user_id!=\"null\"}[5m])) by (type,name)",
       "legendFormat": "{{type}}: {{name}} (not null)"
      },
      {
       "expr": "sum(increase(rocketchat_ddp_rate_limit_exceeded{DeploymentName=\"$deployment\", user_id=\"null\"}[5m])) by (type,name)",
       "legendFormat": "{{type}}: {{name}} (null)"
      }
     ]
    },
    {
     "title": "Limit by userId",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(rocketchat_ddp_rate_limit_exceeded[5m])) by (user_id)",
       "legendFormat": "{{user_id}}"
      }
     ]
    },
    {
     "title": "Limit by connectionId",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(rocketchat_ddp_rate_limit_exceeded{DeploymentName=\"$deployment\", user_id!=\"null\"}[5m])) by (connection_id)",
       "legendFormat": "{{connection_id}} (not null)"
      },
      {
       "expr": "sum(increase(rocketchat_ddp_rate_limit_exceeded{DeploymentName=\"$deployment\", user_id=\"null\"}[5m])) by (connection_id)",
       "legendFormat": "{{connection_id}} (null)"
      }
     ]
    }
   ]
  },
  { "title": "RocketChat Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Messages Sent (30m)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(rocketchat_message_sent[30m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Messages Sent Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "max(rocketchat_messages_total)", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Users Presence",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "avg(rocketchat_users_online)", "legendFormat": "Online" },
    { "expr": "avg(rocketchat_users_away)", "legendFormat": "Away" }
   ]
  },
  {
   "title": "Users & Sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rocketchat_ddp_connected_users)",
     "legendFormat": "Connected Users"
    },
    {
     "expr": "sum(rocketchat_ddp_sessions_count)",
     "legendFormat": "All Sessions"
    },
    {
     "expr": "sum(rocketchat_ddp_sessions_auth)",
     "legendFormat": "Authenticated Sessions "
    }
   ]
  },
  {
   "title": "Web Socket Connections per pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rocketchat_ddp_connected_users", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Apps Installed / Disabled / Failed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rocketchat_apps_installed", "legendFormat": "{{instance}} - installed" },
    { "expr": "rocketchat_apps_enabled", "legendFormat": "{{instance}} - enabled" },
    { "expr": "rocketchat_apps_failed", "legendFormat": "{{instance}} - failed" }
   ]
  },
  {
   "title": "Oplog",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(increase(rocketchat_oplog[5m])) by (collection,op)",
     "legendFormat": "{{collection}}/{{op}}"
    }
   ]
  },
  {
   "title": "Oplog By instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(increase(rocketchat_oplog[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Oplog Queue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rocketchat_oplog_queue", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Push Queue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 120 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rocketchat_push_queue", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Meteor Facts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 129 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rocketchat_meteor_facts) by (pkg, fact)",
     "legendFormat": "{{pkg}} {{fact}}"
    }
   ]
  },
  {
   "title": "Total of Users",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 138 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    { "expr": "max(rocketchat_users_total)", "legendFormat": "Users" }
   ]
  },
  {
   "title": "Total of Rooms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 138 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    { "expr": "max(rocketchat_rooms_total)", "legendFormat": "Rooms" }
   ]
  },
  {
   "title": "Notifications / Minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 146 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum(increase(rocketchat_notification_sent[5m])) by (notification_type)",
     "legendFormat": "{{notification_type}}"
    }
   ]
  },
  {
   "title": "Methods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 155 },
   "collapsed": true,
   "panels": [
    {
     "title": "Meteor Methods Total Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rocketchat_meteor_methods) by (method) * sum(increase(rocketchat_meteor_methods_count[5m])) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Meteor Methods Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rocketchat_meteor_methods) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Meteor Methods Calls / Minute",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(rocketchat_meteor_methods_count[5m])) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 156 },
   "collapsed": true,
   "panels": [
    {
     "title": "Meteor Subscription Total Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rocketchat_meteor_subscriptions) by (subscription) * sum(increase(rocketchat_meteor_subscriptions_count[5m])) by (subscription)",
       "legendFormat": "{{subscription}}"
      }
     ]
    },
    {
     "title": "Meteor Subscription Times",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rocketchat_meteor_subscriptions) by (subscription)",
       "legendFormat": "{{subscription}}"
      }
     ]
    },
    {
     "title": "Meteor Subscription Calls / Minute",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(rocketchat_meteor_subscriptions_count[5m])) by (subscription)",
       "legendFormat": "{{subscription}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Callbacks & Hooks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 157 },
   "collapsed": true,
   "panels": [
    {
     "title": "Callbacks Total Times",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rocketchat_callbacks) by (callback) * sum(increase(rocketchat_callbacks_count[5m])) by (callback)",
       "legendFormat": "{{callback}}"
      }
     ]
    },
    {
     "title": "Callbacks Times",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(irate(rocketchat_callbacks[5m])) by (callback)",
       "legendFormat": "{{callback}}"
      }
     ]
    },
    {
     "title": "Callbacks Calls / Minute",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(increase(rocketchat_callbacks_count[5m])) by (callback)",
       "legendFormat": "{{callback}}"
      }
     ]
    },
    {
     "title": "Hooks Total Times",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rocketchat_hooks) by (hook) * sum(increase(rocketchat_hooks_count[5m])) by (hook)",
       "legendFormat": "{{hook}}"
      }
     ]
    },
    {
     "title": "Hooks Times",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(irate(rocketchat_hooks[5m])) by (hook)",
       "legendFormat": "{{hook}}"
      }
     ]
    },
    {
     "title": "Hooks Calls / Minute",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(increase(rocketchat_hooks_count[5m])) by (hook)",
       "legendFormat": "{{hook}}"
      }
     ]
    }
   ]
  },
  {
   "title": "REST API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 158 },
   "collapsed": true,
   "panels": [
    {
     "title": "REST API Total Times",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rocketchat_rest_api) by (entrypoint) * sum(increase(rocketchat_rest_api_count[5m])) by (entrypoint)",
       "legendFormat": "{{entrypoint}}"
      }
     ]
    },
    {
     "title": "REST API Times",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(irate(rocketchat_rest_api[5m])) by (entrypoint)",
       "legendFormat": "{{entrypoint}}"
      }
     ]
    },
    {
     "title": "REST API Calls / Minute",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(rocketchat_rest_api_count[5m])) by (entrypoint)",
       "legendFormat": "{{entrypoint}}"
      }
     ]
    }
   ]
  }
 ]
}